
# name: Deploy to Production

# on:
#   pull_request:
#     types:
#       - closed

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install Node.js and npm
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14

#       - name: Install dependencies
#         run: npm install

#       - name: Deploy to Production
#         if: github.event.pull_request.merged == true
#         run: npm run deploy

