name: Deploy to Production

on:
  pull_request:
    types:
      - closed

jobs:
  Deploy to Prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
         if: github.event.pull_request.merged == true
        run: npm run build
